/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 4.8.6
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QMainWindow>
#include <QtGui/QPushButton>
#include <QtGui/QStackedWidget>
#include <QtGui/QTextBrowser>
#include <QtGui/QTextEdit>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QPushButton *Caesar;
    QPushButton *Keyword;
    QPushButton *Vigenere;
    QPushButton *Autokey;
    QPushButton *Playfair;
    QPushButton *Permutation;
    QPushButton *C_Permutation;
    QPushButton *RC4;
    QPushButton *DES;
    QPushButton *RSA;
    QStackedWidget *stackedWidget;
    QWidget *page;
    QLabel *label;
    QLabel *label_13;
    QLineEdit *key_Caesar;
    QWidget *page_2;
    QLabel *label_2;
    QLabel *label_14;
    QLineEdit *key_keyword;
    QWidget *page_3;
    QLabel *label_3;
    QLabel *label_15;
    QLineEdit *key_Vigenere;
    QWidget *page_4;
    QLabel *label_4;
    QLabel *label_16;
    QLineEdit *key_Autokey;
    QWidget *page_5;
    QLabel *label_5;
    QLabel *label_17;
    QLineEdit *key_Playfair;
    QWidget *page_6;
    QLabel *label_6;
    QLabel *label_19;
    QLineEdit *key_per;
    QWidget *page_7;
    QLabel *label_7;
    QLabel *label_18;
    QLineEdit *key_C_per;
    QWidget *page_8;
    QLabel *label_8;
    QWidget *page_9;
    QLabel *label_9;
    QLabel *label_26;
    QLineEdit *key_DES;
    QWidget *page_10;
    QLabel *label_10;
    QLabel *label_24;
    QLineEdit *e;
    QLabel *label_25;
    QLineEdit *n_1;
    QLabel *label_27;
    QLabel *label_28;
    QLineEdit *d;
    QLabel *label_29;
    QLineEdit *n_2;
    QLabel *label_30;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_31;
    QWidget *page_11;
    QLabel *label_32;
    QLineEdit *DH_1;
    QLineEdit *DH_2;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLineEdit *DH_g;
    QLineEdit *DH_p;
    QTextEdit *Plaintext;
    QTextBrowser *Ciphertext;
    QLineEdit *lu;
    QPushButton *file;
    QPushButton *Encrypt;
    QPushButton *Decrypt;
    QLabel *label_11;
    QLabel *label_12;
    QPushButton *DH;
    QPushButton *Clean;
    QPushButton *Send;
    QPushButton *Socket;
    QPushButton *connect;
    QLineEdit *IP;
    QPushButton *Receive;
    QPushButton *disconnect;
    QLabel *label_20;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(644, 671);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        Caesar = new QPushButton(centralWidget);
        Caesar->setObjectName(QString::fromUtf8("Caesar"));
        Caesar->setGeometry(QRect(10, 220, 160, 45));
        QFont font;
        font.setPointSize(15);
        font.setBold(true);
        font.setWeight(75);
        Caesar->setFont(font);
        Caesar->setStyleSheet(QString::fromUtf8("QPushButton { background-color: rgb(123, 123, 123); border-radius: 0 px; color: rgb(255, 255, 255); } QPushButton:hover { background-color: rgb(81, 81, 81); }"));
        Keyword = new QPushButton(centralWidget);
        Keyword->setObjectName(QString::fromUtf8("Keyword"));
        Keyword->setGeometry(QRect(10, 320, 160, 45));
        Keyword->setFont(font);
        Keyword->setStyleSheet(QString::fromUtf8("QPushButton { background-color: rgb(123, 123, 123); border-radius: 0 px; color: rgb(255, 255, 255); } QPushButton:hover { background-color: rgb(81, 81, 81); }"));
        Vigenere = new QPushButton(centralWidget);
        Vigenere->setObjectName(QString::fromUtf8("Vigenere"));
        Vigenere->setGeometry(QRect(10, 120, 160, 45));
        Vigenere->setFont(font);
        Vigenere->setStyleSheet(QString::fromUtf8("QPushButton { background-color: rgb(123, 123, 123); border-radius: 0 px; color: rgb(255, 255, 255); } QPushButton:hover { background-color: rgb(81, 81, 81); }"));
        Autokey = new QPushButton(centralWidget);
        Autokey->setObjectName(QString::fromUtf8("Autokey"));
        Autokey->setGeometry(QRect(10, 170, 160, 45));
        Autokey->setFont(font);
        Autokey->setStyleSheet(QString::fromUtf8("QPushButton { background-color: rgb(123, 123, 123); border-radius: 0 px; color: rgb(255, 255, 255); } QPushButton:hover { background-color: rgb(81, 81, 81); }"));
        Playfair = new QPushButton(centralWidget);
        Playfair->setObjectName(QString::fromUtf8("Playfair"));
        Playfair->setGeometry(QRect(10, 470, 160, 45));
        Playfair->setFont(font);
        Playfair->setStyleSheet(QString::fromUtf8("QPushButton { background-color: rgb(123, 123, 123); border-radius: 0 px; color: rgb(255, 255, 255); } QPushButton:hover { background-color: rgb(81, 81, 81); }"));
        Permutation = new QPushButton(centralWidget);
        Permutation->setObjectName(QString::fromUtf8("Permutation"));
        Permutation->setGeometry(QRect(10, 270, 160, 45));
        Permutation->setFont(font);
        Permutation->setStyleSheet(QString::fromUtf8("QPushButton { background-color: rgb(123, 123, 123); border-radius: 0 px; color: rgb(255, 255, 255); } QPushButton:hover { background-color: rgb(81, 81, 81); }"));
        C_Permutation = new QPushButton(centralWidget);
        C_Permutation->setObjectName(QString::fromUtf8("C_Permutation"));
        C_Permutation->setGeometry(QRect(10, 70, 161, 45));
        C_Permutation->setFont(font);
        C_Permutation->setStyleSheet(QString::fromUtf8("QPushButton { background-color: rgb(123, 123, 123); border-radius: 0 px; color: rgb(255, 255, 255); } QPushButton:hover { background-color: rgb(81, 81, 81); }"));
        RC4 = new QPushButton(centralWidget);
        RC4->setObjectName(QString::fromUtf8("RC4"));
        RC4->setGeometry(QRect(10, 370, 160, 45));
        RC4->setFont(font);
        RC4->setStyleSheet(QString::fromUtf8("QPushButton { background-color: rgb(123, 123, 123); border-radius: 0 px; color: rgb(255, 255, 255); } QPushButton:hover { background-color: rgb(81, 81, 81); }"));
        DES = new QPushButton(centralWidget);
        DES->setObjectName(QString::fromUtf8("DES"));
        DES->setGeometry(QRect(10, 420, 160, 45));
        DES->setFont(font);
        DES->setStyleSheet(QString::fromUtf8("QPushButton { background-color: rgb(123, 123, 123); border-radius: 0 px; color: rgb(255, 255, 255); } QPushButton:hover { background-color: rgb(81, 81, 81); }"));
        RSA = new QPushButton(centralWidget);
        RSA->setObjectName(QString::fromUtf8("RSA"));
        RSA->setGeometry(QRect(10, 20, 160, 45));
        RSA->setFont(font);
        RSA->setStyleSheet(QString::fromUtf8("QPushButton { background-color: rgb(123, 123, 123); border-radius: 0 px; color: rgb(255, 255, 255); } QPushButton:hover { background-color: rgb(81, 81, 81); }"));
        stackedWidget = new QStackedWidget(centralWidget);
        stackedWidget->setObjectName(QString::fromUtf8("stackedWidget"));
        stackedWidget->setGeometry(QRect(180, 10, 371, 101));
        QFont font1;
        font1.setPointSize(20);
        font1.setBold(true);
        font1.setWeight(75);
        stackedWidget->setFont(font1);
        page = new QWidget();
        page->setObjectName(QString::fromUtf8("page"));
        label = new QLabel(page);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(110, 10, 241, 30));
        QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(label->sizePolicy().hasHeightForWidth());
        label->setSizePolicy(sizePolicy);
        label->setFont(font1);
        label->setLayoutDirection(Qt::LeftToRight);
        label->setAlignment(Qt::AlignCenter);
        label_13 = new QLabel(page);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(20, 60, 161, 31));
        QFont font2;
        font2.setPointSize(15);
        label_13->setFont(font2);
        key_Caesar = new QLineEdit(page);
        key_Caesar->setObjectName(QString::fromUtf8("key_Caesar"));
        key_Caesar->setGeometry(QRect(180, 60, 51, 31));
        QFont font3;
        font3.setPointSize(12);
        key_Caesar->setFont(font3);
        stackedWidget->addWidget(page);
        page_2 = new QWidget();
        page_2->setObjectName(QString::fromUtf8("page_2"));
        label_2 = new QLabel(page_2);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(110, 10, 210, 30));
        label_2->setFont(font1);
        label_2->setAlignment(Qt::AlignCenter);
        label_14 = new QLabel(page_2);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(20, 60, 161, 31));
        label_14->setFont(font2);
        key_keyword = new QLineEdit(page_2);
        key_keyword->setObjectName(QString::fromUtf8("key_keyword"));
        key_keyword->setGeometry(QRect(180, 60, 141, 31));
        key_keyword->setFont(font3);
        stackedWidget->addWidget(page_2);
        page_3 = new QWidget();
        page_3->setObjectName(QString::fromUtf8("page_3"));
        label_3 = new QLabel(page_3);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(100, 10, 230, 30));
        label_3->setFont(font1);
        label_3->setAlignment(Qt::AlignCenter);
        label_15 = new QLabel(page_3);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(20, 60, 161, 31));
        label_15->setFont(font2);
        key_Vigenere = new QLineEdit(page_3);
        key_Vigenere->setObjectName(QString::fromUtf8("key_Vigenere"));
        key_Vigenere->setGeometry(QRect(180, 60, 141, 31));
        key_Vigenere->setFont(font3);
        stackedWidget->addWidget(page_3);
        page_4 = new QWidget();
        page_4->setObjectName(QString::fromUtf8("page_4"));
        label_4 = new QLabel(page_4);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(80, 10, 270, 30));
        label_4->setFont(font1);
        label_4->setAlignment(Qt::AlignCenter);
        label_16 = new QLabel(page_4);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(20, 60, 161, 31));
        label_16->setFont(font2);
        key_Autokey = new QLineEdit(page_4);
        key_Autokey->setObjectName(QString::fromUtf8("key_Autokey"));
        key_Autokey->setGeometry(QRect(180, 60, 141, 31));
        key_Autokey->setFont(font3);
        stackedWidget->addWidget(page_4);
        page_5 = new QWidget();
        page_5->setObjectName(QString::fromUtf8("page_5"));
        label_5 = new QLabel(page_5);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(100, 10, 230, 30));
        label_5->setAlignment(Qt::AlignCenter);
        label_17 = new QLabel(page_5);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(20, 60, 161, 31));
        label_17->setFont(font2);
        key_Playfair = new QLineEdit(page_5);
        key_Playfair->setObjectName(QString::fromUtf8("key_Playfair"));
        key_Playfair->setGeometry(QRect(180, 60, 141, 31));
        key_Playfair->setFont(font3);
        stackedWidget->addWidget(page_5);
        page_6 = new QWidget();
        page_6->setObjectName(QString::fromUtf8("page_6"));
        label_6 = new QLabel(page_6);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(80, 10, 270, 30));
        label_6->setAlignment(Qt::AlignCenter);
        label_19 = new QLabel(page_6);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(20, 60, 161, 31));
        label_19->setFont(font2);
        key_per = new QLineEdit(page_6);
        key_per->setObjectName(QString::fromUtf8("key_per"));
        key_per->setGeometry(QRect(180, 60, 141, 31));
        key_per->setFont(font3);
        stackedWidget->addWidget(page_6);
        page_7 = new QWidget();
        page_7->setObjectName(QString::fromUtf8("page_7"));
        label_7 = new QLabel(page_7);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(80, 10, 270, 30));
        label_7->setAlignment(Qt::AlignCenter);
        label_18 = new QLabel(page_7);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(20, 60, 161, 31));
        label_18->setFont(font2);
        key_C_per = new QLineEdit(page_7);
        key_C_per->setObjectName(QString::fromUtf8("key_C_per"));
        key_C_per->setGeometry(QRect(180, 60, 141, 31));
        key_C_per->setFont(font3);
        stackedWidget->addWidget(page_7);
        page_8 = new QWidget();
        page_8->setObjectName(QString::fromUtf8("page_8"));
        label_8 = new QLabel(page_8);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(130, 10, 170, 30));
        label_8->setAlignment(Qt::AlignCenter);
        stackedWidget->addWidget(page_8);
        page_9 = new QWidget();
        page_9->setObjectName(QString::fromUtf8("page_9"));
        label_9 = new QLabel(page_9);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(130, 10, 170, 30));
        label_9->setAlignment(Qt::AlignCenter);
        label_26 = new QLabel(page_9);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(20, 60, 191, 31));
        label_26->setFont(font2);
        key_DES = new QLineEdit(page_9);
        key_DES->setObjectName(QString::fromUtf8("key_DES"));
        key_DES->setGeometry(QRect(210, 60, 141, 31));
        key_DES->setFont(font3);
        stackedWidget->addWidget(page_9);
        page_10 = new QWidget();
        page_10->setObjectName(QString::fromUtf8("page_10"));
        label_10 = new QLabel(page_10);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(130, 10, 170, 30));
        label_10->setAlignment(Qt::AlignCenter);
        label_24 = new QLabel(page_10);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(66, 50, 20, 20));
        label_24->setFont(font2);
        e = new QLineEdit(page_10);
        e->setObjectName(QString::fromUtf8("e"));
        e->setGeometry(QRect(80, 50, 111, 21));
        QFont font4;
        font4.setPointSize(10);
        e->setFont(font4);
        label_25 = new QLabel(page_10);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(190, 50, 16, 20));
        label_25->setFont(font2);
        n_1 = new QLineEdit(page_10);
        n_1->setObjectName(QString::fromUtf8("n_1"));
        n_1->setGeometry(QRect(200, 50, 111, 20));
        n_1->setFont(font4);
        label_27 = new QLabel(page_10);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(310, 50, 16, 21));
        label_27->setFont(font2);
        label_28 = new QLabel(page_10);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(66, 80, 20, 21));
        label_28->setFont(font2);
        d = new QLineEdit(page_10);
        d->setObjectName(QString::fromUtf8("d"));
        d->setGeometry(QRect(80, 80, 111, 20));
        d->setFont(font4);
        label_29 = new QLabel(page_10);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(190, 81, 20, 20));
        label_29->setFont(font2);
        n_2 = new QLineEdit(page_10);
        n_2->setObjectName(QString::fromUtf8("n_2"));
        n_2->setGeometry(QRect(200, 80, 111, 20));
        n_2->setFont(font4);
        label_30 = new QLabel(page_10);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(310, 80, 16, 21));
        label_30->setFont(font2);
        label_21 = new QLabel(page_10);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(20, 50, 51, 20));
        label_21->setFont(font2);
        label_22 = new QLabel(page_10);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(20, 80, 51, 20));
        label_22->setFont(font2);
        label_23 = new QLabel(page_10);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(320, 50, 41, 21));
        QFont font5;
        font5.setPointSize(10);
        font5.setBold(false);
        font5.setWeight(50);
        label_23->setFont(font5);
        label_31 = new QLabel(page_10);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(320, 80, 41, 21));
        label_31->setFont(font5);
        stackedWidget->addWidget(page_10);
        page_11 = new QWidget();
        page_11->setObjectName(QString::fromUtf8("page_11"));
        label_32 = new QLabel(page_11);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(130, 10, 211, 31));
        label_32->setAlignment(Qt::AlignCenter);
        DH_1 = new QLineEdit(page_11);
        DH_1->setObjectName(QString::fromUtf8("DH_1"));
        DH_1->setGeometry(QRect(80, 50, 71, 21));
        DH_1->setFont(font4);
        DH_2 = new QLineEdit(page_11);
        DH_2->setObjectName(QString::fromUtf8("DH_2"));
        DH_2->setGeometry(QRect(100, 80, 121, 21));
        DH_2->setFont(font4);
        DH_2->setAlignment(Qt::AlignCenter);
        label_33 = new QLabel(page_11);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(10, 50, 71, 21));
        label_33->setFont(font2);
        label_34 = new QLabel(page_11);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(10, 80, 91, 21));
        label_34->setFont(font2);
        label_35 = new QLabel(page_11);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(160, 50, 21, 21));
        label_35->setFont(font2);
        label_36 = new QLabel(page_11);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(260, 50, 21, 21));
        label_36->setFont(font2);
        DH_g = new QLineEdit(page_11);
        DH_g->setObjectName(QString::fromUtf8("DH_g"));
        DH_g->setGeometry(QRect(180, 50, 71, 20));
        DH_g->setFont(font4);
        DH_p = new QLineEdit(page_11);
        DH_p->setObjectName(QString::fromUtf8("DH_p"));
        DH_p->setGeometry(QRect(280, 50, 71, 20));
        DH_p->setFont(font4);
        stackedWidget->addWidget(page_11);
        Plaintext = new QTextEdit(centralWidget);
        Plaintext->setObjectName(QString::fromUtf8("Plaintext"));
        Plaintext->setGeometry(QRect(190, 140, 431, 171));
        Plaintext->setFont(font3);
        Ciphertext = new QTextBrowser(centralWidget);
        Ciphertext->setObjectName(QString::fromUtf8("Ciphertext"));
        Ciphertext->setGeometry(QRect(190, 380, 431, 171));
        Ciphertext->setFont(font3);
        lu = new QLineEdit(centralWidget);
        lu->setObjectName(QString::fromUtf8("lu"));
        lu->setGeometry(QRect(190, 320, 361, 31));
        lu->setFont(font4);
        file = new QPushButton(centralWidget);
        file->setObjectName(QString::fromUtf8("file"));
        file->setGeometry(QRect(560, 320, 61, 31));
        file->setFont(font);
        file->setStyleSheet(QString::fromUtf8("QPushButton { background-color: rgb(123, 123, 123); border-radius: 0 px; color: rgb(255, 255, 255); } QPushButton:hover { background-color: rgb(81, 81, 81); }"));
        Encrypt = new QPushButton(centralWidget);
        Encrypt->setObjectName(QString::fromUtf8("Encrypt"));
        Encrypt->setGeometry(QRect(240, 570, 161, 41));
        Encrypt->setFont(font);
        Encrypt->setStyleSheet(QString::fromUtf8("QPushButton { background-color: rgb(123, 123, 123); border-radius: 0 px; color: rgb(255, 255, 255); } QPushButton:hover { background-color: rgb(81, 81, 81); }"));
        Decrypt = new QPushButton(centralWidget);
        Decrypt->setObjectName(QString::fromUtf8("Decrypt"));
        Decrypt->setGeometry(QRect(440, 570, 161, 41));
        Decrypt->setFont(font);
        Decrypt->setStyleSheet(QString::fromUtf8("QPushButton { background-color: rgb(123, 123, 123); border-radius: 0 px; color: rgb(255, 255, 255); } QPushButton:hover { background-color: rgb(81, 81, 81); }"));
        label_11 = new QLabel(centralWidget);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(190, 350, 101, 31));
        QFont font6;
        font6.setPointSize(11);
        font6.setBold(true);
        font6.setWeight(75);
        label_11->setFont(font6);
        label_12 = new QLabel(centralWidget);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(190, 110, 101, 31));
        label_12->setFont(font6);
        DH = new QPushButton(centralWidget);
        DH->setObjectName(QString::fromUtf8("DH"));
        DH->setGeometry(QRect(10, 520, 161, 41));
        DH->setFont(font);
        DH->setStyleSheet(QString::fromUtf8("QPushButton { background-color: rgb(123, 123, 123); border-radius: 0 px; color: rgb(255, 255, 255); } QPushButton:hover { background-color: rgb(81, 81, 81); }"));
        Clean = new QPushButton(centralWidget);
        Clean->setObjectName(QString::fromUtf8("Clean"));
        Clean->setGeometry(QRect(560, 90, 61, 41));
        Clean->setFont(font);
        Clean->setStyleSheet(QString::fromUtf8("QPushButton { background-color: rgb(123, 123, 123); border-radius: 0 px; color: rgb(255, 255, 255); } QPushButton:hover { background-color: rgb(81, 81, 81); }"));
        Send = new QPushButton(centralWidget);
        Send->setObjectName(QString::fromUtf8("Send"));
        Send->setGeometry(QRect(440, 620, 161, 41));
        Send->setFont(font);
        Send->setStyleSheet(QString::fromUtf8("QPushButton { background-color: rgb(123, 123, 123); border-radius: 0 px; color: rgb(255, 255, 255); } QPushButton:hover { background-color: rgb(81, 81, 81); }"));
        Socket = new QPushButton(centralWidget);
        Socket->setObjectName(QString::fromUtf8("Socket"));
        Socket->setGeometry(QRect(10, 620, 61, 41));
        Socket->setFont(font);
        Socket->setStyleSheet(QString::fromUtf8("QPushButton { background-color: rgb(123, 123, 123); border-radius: 0 px; color: rgb(255, 255, 255); } QPushButton:hover { background-color: rgb(81, 81, 81); }"));
        connect = new QPushButton(centralWidget);
        connect->setObjectName(QString::fromUtf8("connect"));
        connect->setGeometry(QRect(80, 620, 61, 41));
        connect->setFont(font);
        connect->setStyleSheet(QString::fromUtf8("QPushButton { background-color: rgb(123, 123, 123); border-radius: 0 px; color: rgb(255, 255, 255); } QPushButton:hover { background-color: rgb(81, 81, 81); }"));
        IP = new QLineEdit(centralWidget);
        IP->setObjectName(QString::fromUtf8("IP"));
        IP->setGeometry(QRect(60, 580, 151, 31));
        QFont font7;
        font7.setPointSize(12);
        font7.setBold(false);
        font7.setWeight(50);
        IP->setFont(font7);
        IP->setAlignment(Qt::AlignCenter);
        Receive = new QPushButton(centralWidget);
        Receive->setObjectName(QString::fromUtf8("Receive"));
        Receive->setGeometry(QRect(240, 620, 161, 41));
        Receive->setFont(font);
        Receive->setStyleSheet(QString::fromUtf8("QPushButton { background-color: rgb(123, 123, 123); border-radius: 0 px; color: rgb(255, 255, 255); } QPushButton:hover { background-color: rgb(81, 81, 81); }"));
        disconnect = new QPushButton(centralWidget);
        disconnect->setObjectName(QString::fromUtf8("disconnect"));
        disconnect->setGeometry(QRect(150, 620, 61, 41));
        disconnect->setFont(font);
        disconnect->setStyleSheet(QString::fromUtf8("QPushButton { background-color: rgb(123, 123, 123); border-radius: 0 px; color: rgb(255, 255, 255); } QPushButton:hover { background-color: rgb(81, 81, 81); }"));
        label_20 = new QLabel(centralWidget);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(10, 580, 61, 31));
        QFont font8;
        font8.setPointSize(10);
        font8.setBold(true);
        font8.setWeight(75);
        label_20->setFont(font8);
        MainWindow->setCentralWidget(centralWidget);

        retranslateUi(MainWindow);

        stackedWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0, QApplication::UnicodeUTF8));
        Caesar->setText(QApplication::translate("MainWindow", "Caesar", 0, QApplication::UnicodeUTF8));
        Keyword->setText(QApplication::translate("MainWindow", "Keyword", 0, QApplication::UnicodeUTF8));
        Vigenere->setText(QApplication::translate("MainWindow", "Vigenere", 0, QApplication::UnicodeUTF8));
        Autokey->setText(QApplication::translate("MainWindow", "Autokey", 0, QApplication::UnicodeUTF8));
        Playfair->setText(QApplication::translate("MainWindow", "Playfair", 0, QApplication::UnicodeUTF8));
        Permutation->setText(QApplication::translate("MainWindow", "Permutation", 0, QApplication::UnicodeUTF8));
        C_Permutation->setText(QApplication::translate("MainWindow", "Column_Per", 0, QApplication::UnicodeUTF8));
        RC4->setText(QApplication::translate("MainWindow", "RC4", 0, QApplication::UnicodeUTF8));
        DES->setText(QApplication::translate("MainWindow", "DES", 0, QApplication::UnicodeUTF8));
        RSA->setText(QApplication::translate("MainWindow", "RSA", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("MainWindow", "Caesar cipher", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("MainWindow", "Input the Key:", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("MainWindow", "Keyword cipher", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("MainWindow", "Input the Key:", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("MainWindow", "Vigenere cipher", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("MainWindow", "Input the Key:", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("MainWindow", "Autokey ciphertext", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("MainWindow", "Input the Key:", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("MainWindow", "Playfair cipher", 0, QApplication::UnicodeUTF8));
        label_17->setText(QApplication::translate("MainWindow", "Input the Key:", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("MainWindow", "Permutation cipher", 0, QApplication::UnicodeUTF8));
        label_19->setText(QApplication::translate("MainWindow", "Input the Key:", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("MainWindow", "Column Permutation", 0, QApplication::UnicodeUTF8));
        label_18->setText(QApplication::translate("MainWindow", "Input the Key:", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("MainWindow", "RC4", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("MainWindow", "DES", 0, QApplication::UnicodeUTF8));
        label_26->setText(QApplication::translate("MainWindow", "Input the Key(8):", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("MainWindow", "RSA", 0, QApplication::UnicodeUTF8));
        label_24->setText(QApplication::translate("MainWindow", "(", 0, QApplication::UnicodeUTF8));
        label_25->setText(QApplication::translate("MainWindow", ",", 0, QApplication::UnicodeUTF8));
        label_27->setText(QApplication::translate("MainWindow", ")", 0, QApplication::UnicodeUTF8));
        label_28->setText(QApplication::translate("MainWindow", "(", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("MainWindow", ",", 0, QApplication::UnicodeUTF8));
        label_30->setText(QApplication::translate("MainWindow", ")", 0, QApplication::UnicodeUTF8));
        label_21->setText(QApplication::translate("MainWindow", "\345\205\254\351\222\245:", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("MainWindow", "\347\247\201\351\222\245:", 0, QApplication::UnicodeUTF8));
        label_23->setText(QApplication::translate("MainWindow", "(\350\207\252\345\212\250)", 0, QApplication::UnicodeUTF8));
        label_31->setText(QApplication::translate("MainWindow", "(\350\207\252\345\212\250)", 0, QApplication::UnicodeUTF8));
        label_32->setText(QApplication::translate("MainWindow", "DH(Caesar)", 0, QApplication::UnicodeUTF8));
        DH_2->setText(QString());
        label_33->setText(QApplication::translate("MainWindow", "Input:", 0, QApplication::UnicodeUTF8));
        label_34->setText(QApplication::translate("MainWindow", "Results:", 0, QApplication::UnicodeUTF8));
        label_35->setText(QApplication::translate("MainWindow", "g:", 0, QApplication::UnicodeUTF8));
        label_36->setText(QApplication::translate("MainWindow", "p:", 0, QApplication::UnicodeUTF8));
        lu->setText(QString());
        file->setText(QApplication::translate("MainWindow", "Flie", 0, QApplication::UnicodeUTF8));
        Encrypt->setText(QApplication::translate("MainWindow", "Encrypt", 0, QApplication::UnicodeUTF8));
        Decrypt->setText(QApplication::translate("MainWindow", "Decrypt", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("MainWindow", "\345\212\240/\350\247\243\345\257\206\347\273\223\346\236\234\357\274\232", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("MainWindow", "\345\212\240/\350\247\243\345\257\206\345\206\205\345\256\271\357\274\232", 0, QApplication::UnicodeUTF8));
        DH->setText(QApplication::translate("MainWindow", "DH", 0, QApplication::UnicodeUTF8));
        Clean->setText(QApplication::translate("MainWindow", "Clean", 0, QApplication::UnicodeUTF8));
        Send->setText(QApplication::translate("MainWindow", "Send", 0, QApplication::UnicodeUTF8));
        Socket->setText(QApplication::translate("MainWindow", "\345\220\257\345\212\250", 0, QApplication::UnicodeUTF8));
        connect->setText(QApplication::translate("MainWindow", "\350\277\236\346\216\245", 0, QApplication::UnicodeUTF8));
        IP->setText(QApplication::translate("MainWindow", "\346\234\252\350\277\236\346\216\245", 0, QApplication::UnicodeUTF8));
        Receive->setText(QApplication::translate("MainWindow", "Receive", 0, QApplication::UnicodeUTF8));
        disconnect->setText(QApplication::translate("MainWindow", "\346\226\255\345\274\200", 0, QApplication::UnicodeUTF8));
        label_20->setText(QApplication::translate("MainWindow", "\350\277\236\346\216\245IP:", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
